config/routes.rb
Rails.application.routes.draw do
	get 'game_holders/play'

	get 'game_holders/new'

	get 'game_holders/index'

	get 'game_holders/show'

	root 'game_holders#index'

	resources :game_holders
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/game.rb
class Game < Gosu::Window
  def initialize(x,y)
    super(x, y, false)
    self.caption = "Let's play a game!"
 
    @background_image = Gosu::Image.new("public/Space.png", {})

    @player = Player.new(self)
    @player.warp(320, 240)
  end

   def update
    if button_down? Gosu::KbLeft or button_down? Gosu::GpLeft then
      @player.turn_left
    end
    if button_down? Gosu::KbRight or button_down? Gosu::GpRight then
      @player.turn_right
    end
    if button_down? Gosu::KbUp or button_down? Gosu::GpButton0 then
      @player.accelerate
    end
    @player.move
  end
 
  def draw
    xsize = @background_image.width
    ysize = @background_image.height
    xscale = width/xsize
    yscale = height/ysize
    @player.draw
    @background_image.draw(0,0,0,xscale,yscale)
  end

   def button_down(id)
    if id == Gosu::KbEscape
      close
    end
  end
end

app/models/game_holder.rb
class GameHolder < ApplicationRecord
	validates :title, presence: true
	validates :x, numericality: {only_integer: true}
	validates :y, numericality: {only_integer: true}

	def makeGame()
		@igame = Game.new(self.x,self.y)
	end
	def igame
		@igame = Game.new(self.x,self.y)
	end
end

app/models/player.rb
# app/models/player.rb
class Player
  def initialize(window)
    @image = Gosu::Image.new("public/Skyrim.png", {})
    @x = @y = @vel_x = @vel_y = @angle = 0.0
    @score = 0
  end
 
  def warp(x, y)
    @x, @y = x, y
  end
 
  def turn_left
    @angle -= 4.5
  end
 
  def turn_right
    @angle += 4.5
  end
 
  def accelerate
    @vel_x += Gosu::offset_x(@angle, 0.5)
    @vel_y += Gosu::offset_y(@angle, 0.5)
  end
 
  def move
    @x += @vel_x
    @y += @vel_y
    @x %= 640
    @y %= 480
 
    @vel_x *= 0.95
    @vel_y *= 0.95
  end
 
  def draw
    @image.draw_rot(@x, @y, 1, @angle)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_holders_controller.rb
class GameHoldersController < ApplicationController
	def new
		@game_holder = GameHolder.new
	end

	def play
		@game_holder = GameHolder.find(params[:id])
	end

	def index
		@game_holder = GameHolder.all
	end

	def show
		@game_holder = GameHolder.find(params[:id])
		@game_holder.makeGame()
		igame = @game_holder.igame
		igame.show
	end

	def create
		@game_holder = GameHolder.new(holder_params)
		@game_holder.makeGame()
		if @game_holder.save
			redirect_to @game_holder
		else
			render 'new'
		end
	end

	private

		def holder_params
			params.require(:game_holder).permit(:x,:y,:description,:title)
		end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)
	end

	private

		def game_params
			params.require(:game).permit(:x,:y)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_holders_helper.rb
module GameHoldersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/game_holders/index.html.erb
<h1>Game List</h1>
<% @game_holder.each do |x| %>
	<%= link_to "Play", game_holder_path(x)%>
	<%= x.title %>
	<br>
<% end %>

app/views/game_holders/new.html.erb
<h1>New Game</h1>
<%= form_with scope: :game_holder, url: game_holders_path do |form| %>

  <% if @game_holder.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game_holder.errors.count, "error") %> prohibited
        this game from being made:
      </h2>
      <ul>
        <% @game_holder.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br> 
    <%= form.text_field(:title) %>
  </p>

  <p>
    <%= form.label :x %><br> 
    <%= form.text_field(:x) %>
  </p>

  <p>
    <%= form.label :y %><br> 
    <%= form.text_field(:y) %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p> 
<% end %>

<%= link_to 'Back', game_holders_path %>

app/views/game_holders/play.html.erb
<% @game_holder.each do |h| %>
	h.show
<% end %>

app/views/game_holders/show.html.erb
<%= @game_holder.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glitter</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Navigation -->
	    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <%= link_to "Game Manager", root_url, class: "navbar-brand" %>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">
	                    <li>
	                        <%= link_to "New Game" , new_game_holder_path %>
	                    </li>
	                    <%- if current_user %>
	                   	<li>
	                        <%= link_to "Logout" , destroy_user_session_path, method: :delete, confirm: "Are you sure?"%>
	                    </li>
	                    <% else %>
	                    <li>
	                        <%= link_to "Login" , new_user_session_path %>
	                    </li>
	                    <li>
	                        <%= link_to "Register" , new_user_registration_path %>
	                    </li>
	                    <% end %>
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	        </div>
	        <!-- /.container -->
	    </nav>

	    <!-- Page Content -->
	    <div class="container">

	    	<div class="row">
		    	<div class="col-lg-12 text-center">
			    	<% flash.each do |a, b| %>
			    		<div class="alert alert-success"><%= b %></div>
			    	<%end%>
		    		<%= yield %>
		    	</div>
	    	</div>
	    	<!-- /.row -->
	    </div>
	    <!-- /.container -->
	  <style>body{padding-top:70px;}</style>
	</body>
	</html>